---
name: Bug Report
description: Report a bug or issue with KidsChores
title: "[BUG] "
labels: bug
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Please fill out this form to report a bug with KidsChores.**

  - type: input
    id: version
    attributes:
      label: KidsChores Version
      description: "What version are you running? (check Settings or docker image tag)"
      placeholder: "e.g., 0.7.0"
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      description: "How is KidsChores deployed?"
      options:
        - Docker Compose
        - Docker (manual)
        - Local development (npm run dev)
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: "Which browser are you using?"
      placeholder: "e.g., Chrome 120, Safari 17, Firefox 121"
    validations:
      required: true

  - type: checkboxes
    id: prior_issue_check
    attributes:
      label: Did you check for existing issues?
      options:
        - label: Yes, I have checked for existing issues
          required: true

  - type: textarea
    id: issue_description
    attributes:
      label: Describe the Bug
      description: "A clear and concise description of what the bug is."
      placeholder: "What happened? What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: "How can we reproduce this issue?"
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Paste any relevant logs from `docker compose logs` or browser console."
      render: text

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: "Add any other context, screenshots, or information about the problem."
---
