/**
 * Curated icon vocabulary for chores, categories, and rewards.
 *
 * Single source of truth for:
 *  - the IconPicker grid (id + label + search keywords)
 *  - DynamicIcon's name→component resolution
 *  - the emoji→icon mapping used at render time for not-yet-migrated data
 *    (mirrored as EMOJI_TO_LUCIDE in backend/app/migrations/icon_migration.py —
 *    keep the two in sync)
 *
 * v0.12: content icons render as full-color Twemoji artwork (vendored in
 * twemoji-icons.tsx, regenerated by scripts/fetch-twemoji.mjs). The STORED
 * names are unchanged — they remain the stable lucide-kebab ids introduced in
 * v0.11, only the Component column changed. UI chrome (nav, buttons, form
 * affordances) stays monochrome lucide.
 */
import { TWEMOJI_ICONS, type IconComponent } from './twemoji-icons';

export type { IconComponent } from './twemoji-icons';

const T = (name: string): IconComponent => TWEMOJI_ICONS[name];

export interface IconEntry {
  id: string;          // stable stored name (lucide kebab-case heritage) — the value stored in the DB
  label: string;       // human label in the picker
  keywords: string;    // extra search terms
  Component: IconComponent;
}

// The picker grid (ordered roughly by chore-domain usefulness)
export const ICON_CATALOG: IconEntry[] = [
  { id: 'brush', label: 'Cleaning', keywords: 'sweep broom scrub tidy', Component: T('brush') },
  { id: 'sparkles', label: 'Sparkle', keywords: 'clean shine polish', Component: T('sparkles') },
  { id: 'bed', label: 'Bed', keywords: 'bedroom sleep make', Component: T('bed') },
  { id: 'utensils', label: 'Dishes', keywords: 'kitchen table eat fork', Component: T('utensils') },
  { id: 'cooking-pot', label: 'Cooking', keywords: 'kitchen meal pot', Component: T('cooking-pot') },
  { id: 'shower-head', label: 'Bathroom', keywords: 'shower bath wash', Component: T('shower-head') },
  { id: 'sofa', label: 'Living room', keywords: 'couch tidy', Component: T('sofa') },
  { id: 'trees', label: 'Outdoor', keywords: 'yard garden outside', Component: T('trees') },
  { id: 'sprout', label: 'Plants', keywords: 'water grow garden', Component: T('sprout') },
  { id: 'trash-2', label: 'Trash', keywords: 'garbage bin rubbish', Component: T('trash-2') },
  { id: 'shirt', label: 'Laundry', keywords: 'clothes fold', Component: T('shirt') },
  { id: 'washing-machine', label: 'Washing', keywords: 'laundry machine basket', Component: T('washing-machine') },
  { id: 'book-open', label: 'Homework', keywords: 'school study', Component: T('book-open') },
  { id: 'book', label: 'Reading', keywords: 'book story', Component: T('book') },
  { id: 'backpack', label: 'School bag', keywords: 'school pack', Component: T('backpack') },
  { id: 'pencil', label: 'Writing', keywords: 'draw write', Component: T('pencil') },
  { id: 'dog', label: 'Dog', keywords: 'pet walk feed', Component: T('dog') },
  { id: 'cat', label: 'Cat', keywords: 'pet litter feed', Component: T('cat') },
  { id: 'paw-print', label: 'Pets', keywords: 'animal care', Component: T('paw-print') },
  { id: 'smartphone', label: 'Screen time', keywords: 'phone tablet', Component: T('smartphone') },
  { id: 'gamepad-2', label: 'Games', keywords: 'video game play', Component: T('gamepad-2') },
  { id: 'clapperboard', label: 'Movie', keywords: 'film night tv', Component: T('clapperboard') },
  { id: 'tv', label: 'TV', keywords: 'television show', Component: T('tv') },
  { id: 'music', label: 'Music', keywords: 'song practice', Component: T('music') },
  { id: 'palette', label: 'Art', keywords: 'paint craft draw', Component: T('palette') },
  { id: 'bike', label: 'Bike', keywords: 'ride cycle', Component: T('bike') },
  { id: 'car', label: 'Car', keywords: 'wash drive', Component: T('car') },
  { id: 'dumbbell', label: 'Exercise', keywords: 'sport workout', Component: T('dumbbell') },
  { id: 'pizza', label: 'Pizza', keywords: 'dinner food', Component: T('pizza') },
  { id: 'ice-cream-cone', label: 'Ice cream', keywords: 'treat dessert', Component: T('ice-cream-cone') },
  { id: 'moon', label: 'Bedtime', keywords: 'night stay up late', Component: T('moon') },
  { id: 'toy-brick', label: 'Toys', keywords: 'lego play tidy teddy', Component: T('toy-brick') },
  { id: 'gift', label: 'Gift', keywords: 'reward present', Component: T('gift') },
  { id: 'star', label: 'Star', keywords: 'points favorite', Component: T('star') },
  { id: 'heart', label: 'Heart', keywords: 'love kindness', Component: T('heart') },
  { id: 'party-popper', label: 'Party', keywords: 'celebrate fun', Component: T('party-popper') },
  { id: 'folder', label: 'Folder', keywords: 'category general', Component: T('folder') },
];

// Extra resolvable names that aren't in the picker grid (badges/challenges/
// legacy mdi values keep rendering)
const EXTRA_ICONS: Record<string, IconComponent> = {
  'medal': T('medal'),
  'trophy': T('trophy'),
  'trophy-award': T('trophy-award'),
  'award': T('award'),
  'flame': T('flame'),
  'fire': T('fire'),
  'zap': T('zap'),
  'lightning-bolt': T('lightning-bolt'),
  'crown': T('crown'),
  'target': T('target'),
  'rocket': T('rocket'),
  'rocket-launch': T('rocket-launch'),
  'camera': T('camera'),
  'alert': T('alert'),
  'alert-triangle': T('alert-triangle'),
  'clock': T('clock'),
  'calendar': T('calendar'),
  'shopping': T('shopping'),
  'shopping-bag': T('shopping-bag'),
  'cash': T('cash'),
  'television': T('television'),
  'gamepad': T('gamepad'),
  'gamepad-variant': T('gamepad-variant'),
  'bicycle': T('bicycle'),
  'ice-cream': T('ice-cream'),
  'check-circle': T('check-circle'),
};

// name (bare stored name or legacy mdi alias) → component
export const NAME_TO_ICON: Record<string, IconComponent> = {
  ...Object.fromEntries(ICON_CATALOG.map(e => [e.id, e.Component])),
  ...EXTRA_ICONS,
};

// Legacy emoji values (pre-v0.11 data, seeds, and templates) → stored names.
// Mirrored in backend/app/migrations/icon_migration.py — keep in sync.
export const EMOJI_TO_LUCIDE: Record<string, string> = {
  '📁': 'folder',
  '🧹': 'brush',
  '🧽': 'sparkles',
  '🪥': 'brush',
  '🛏️': 'bed',
  '🍽️': 'utensils',
  '🍳': 'cooking-pot',
  '🚿': 'shower-head',
  '🛋️': 'sofa',
  '🌳': 'trees',
  '🌱': 'sprout',
  '🗑️': 'trash-2',
  '👕': 'shirt',
  '🧺': 'washing-machine',
  '📚': 'book-open',
  '📖': 'book',
  '✏️': 'pencil',
  '🐕': 'dog',
  '🐱': 'cat',
  '🐾': 'paw-print',
  '📱': 'smartphone',
  '🎮': 'gamepad-2',
  '🎬': 'clapperboard',
  '🎵': 'music',
  '🍕': 'pizza',
  '🍦': 'ice-cream-cone',
  '🌙': 'moon',
  '🧸': 'toy-brick',
  '🎁': 'gift',
  '⭐': 'star',
  '❤️': 'heart',
  '🏆': 'trophy',
  '🏅': 'medal',
  '🔥': 'flame',
  '👑': 'crown',
  '🚀': 'rocket',
  '📷': 'camera',
  '⚠️': 'alert-triangle',
  '🎉': 'party-popper',
};
